linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unparam
    - prealloc
    - whitespace
    - bodyclose
    - stylecheck

run:
  timeout: 5m

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
