version: '3'

tasks:
  build:
    desc: Build the claude-swarm Go binary
    cmds:
      - go build -o claude-swarm .

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  install:
    desc: Build and install claude-swarm to ~/bin
    cmds:
      - task: build
      - mkdir -p ~/bin
      - cp claude-swarm ~/bin/claude-swarm
      - |
        if ! grep -q 'export PATH="$HOME/bin:$PATH"' ~/.bashrc; then
          echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
          echo "Added ~/bin to PATH in ~/.bashrc"
        else
          echo "~/bin already in PATH"
        fi
      - echo "Run 'source ~/.bashrc' or open a new terminal to apply PATH changes"
      - task: install-statusline

  install-statusline:
    desc: Install the Claude Code status line (token usage bar) into ~/.claude
    cmds:
      - mkdir -p ~/.claude
      - cp statusline-command.sh ~/.claude/statusline-command.sh
      - chmod +x ~/.claude/statusline-command.sh
      - |
        settings=~/.claude/settings.json
        if [ ! -f "$settings" ]; then
          echo '{}' > "$settings"
        fi
        tmp=$(mktemp)
        jq '. + {"statusLine": {"type": "command", "command": "bash ~/.claude/statusline-command.sh"}}' "$settings" > "$tmp"
        mv "$tmp" "$settings"
        echo "Status line configured in $settings"
